# Generated by Django 2.0.13 on 2019-04-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TalleresModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('detalle', models.CharField(max_length=500)),
                ('horas', models.IntegerField()),
                ('cupos', models.IntegerField()),
            ],
        ),
    ]
