# Generated by Django 2.0.13 on 2019-04-30 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Talleres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulantesModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fono', models.IntegerField()),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Talleres.TalleresModelo')),
            ],
        ),
    ]
